#!/usr/bin/env python2
# vim:fileencoding=utf-8
# License: GPLv3 Copyright: 2016, Kovid Goyal <kovid at kovidgoyal.net>

from __future__ import (unicode_literals, division, absolute_import,
                        print_function)

import sys
import os
import subprocess

base = os.path.dirname(os.path.abspath(__file__))


def abspath(x):
    return os.path.abspath(os.path.join(base, x))

arch = sys.argv[-1].decode('utf-8')
if arch not in '64 32'.split():
    raise SystemExit('Usage: build-docker 32|64')
cmd = ('docker', 'build', '-t', ('calibre:' + arch),
       '-f', abspath('linux/dockerfile-{}bit'.format(arch)), abspath('linux')
       )
print(*cmd)

raise SystemExit(subprocess.Popen(cmd).wait())
