FROM ubuntu:precise
MAINTAINER Kovid Goyal "kovid@kovidgoyal.net"

RUN useradd --home-dir=/tmp --uid=1000 --gid=100 kovid
# Basic build environment
RUN apt-get update && apt-get install -y build-essential nasm python-argparse cmake 
# Build time deps for Qt. See http://doc.qt.io/qt-5/linux-requirements.html and https://wiki.qt.io/Building_Qt_5_from_Git
RUN apt-get install -y flex bison gperf ruby libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev xkb-data libglu1-mesa-dev libgtk2.0-dev

RUN apt-get clean
