FROM ubuntu:precise
MAINTAINER Kovid Goyal "kovid@kovidgoyal.net"

RUN useradd --home-dir=/tmp --uid=1000 --gid=100 kovid
RUN apt-get update && apt-get install -y build-essential nasm python-argparse cmake && apt-get clean
